# Generated by Django 3.1.2 on 2020-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracker', '0002_auto_20201022_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hidden',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='panic',
            field=models.BooleanField(default=False),
        ),
    ]
